global:
  scrape_interval: 60s
  evaluation_interval: 60s
  external_labels:
    monitor: 'signoz'
    environment: 'production'

scrape_configs:
  - job_name: 'query-service'
    static_configs:
      - targets: ['query-service:8080']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*'
        action: keep

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
